### ISSUE TITLE
Add ability to change base url

### ISSUE THREAD

**Issue by ljagiela** [andrcuns/allure-publish-action#13]
Hey,

We are using your action with our s3 bucket that is basic-auth protected by cloudfront + lambda function. Your action generates a PR summary that contains link to the bucket that is not working in such config.

It would be great if the plugin had a input to replace a base url for the report.

<img width="535" alt="image" src="https://user-images.githubusercontent.com/12641433/208448278-c77c9820-b35a-45f8-9b09-5d85c42e957e.png">

Now it is: `http://<bucket>.s3.amazonaws.com/<prefix>/3731544215/index.html`

Expected:
- new input, eg: baseUrl, so that url could look like:
`http://<baseUrl>/<prefix>/3731544215/index.html
`

**Comment by andrcuns** [comment]
This sounds reasonable. It would have to be implemented in the [report publisher repo](https://github.com/andrcuns/allure-report-publisher) first though, but I believe it should be a simple enough change.
