### ISSUE TITLE
"Access Denied" Error

### ISSUE THREAD

**Issue by e965** [andrcuns/allure-publish-action#24]
Hi! I'm trying to set up an Allure report deploy for my project, and have encountered this error.

When the action ran for the first time, everything went fine - the data deployed correctly on the s3-bucker. But the second and subsequent launches for some reason gave an `Access Denied` error on "Generating allure report" step.

![image](https://github.com/andrcuns/allure-publish-action/assets/18071040/e78e542a-e091-4dbc-b001-3a5bdd750729)

I've checked several times, the problem is definitely not file system permissions or bucket accesses.

**Comment by andrcuns** [comment]
@e965 Sorry for late response.

There is an option to enable debug logging, You can try that to see if it will show a bit more info where this error is coming from. At the moment, it' s hard to tell what could be the reason for this.
